M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Sun 13 Feb 2022 01:33:08 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-13T01:33:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.4252Y-3.5
X4.4252Y-5.563
X8.0748Y-3.0145
X8.0748Y-5.563
T0
M30
