M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Thu 24 Mar 2022 22:15:36 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-24T22:15:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X112.4Y-88.9
X112.4Y-141.3
X205.1Y-141.3
X205.105Y-48.895
T0
M30
